"""Add current_map_id fk to gamesets_meta

Revision ID: 172d0d0efa2e
Revises: 90a24b8a86dc
Create Date: 2023-01-18 08:49:00.085208

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "172d0d0efa2e"
down_revision = "90a24b8a86dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamesets_meta",
        sa.Column("current_map_id", sa.BigInteger(), nullable=False),
    )
    op.create_foreign_key(
        None, "gamesets_meta", "maps", ["current_map_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "gamesets_meta_current_map_id_fkey",
        "gamesets_meta",
        type_="foreignkey",
    )
    op.drop_column("gamesets_meta", "current_map_id")
    # ### end Alembic commands ###
