"""init

Revision ID: b22b70a2244d
Revises: 
Create Date: 2023-02-10 05:40:13.902733

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b22b70a2244d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", postgresql.BYTEA(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_username"), "users", ["username"], unique=True
    )
    op.create_table(
        "game_sets",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("short_url", sa.String(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_sets_short_url"), "game_sets", ["short_url"], unique=True
    )
    op.create_table(
        "maps",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="_user_id_map_uc"),
    )
    op.create_table(
        "game_sets_meta",
        sa.Column("game_set_id", sa.BigInteger(), nullable=True),
        sa.Column("map_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_set_id"],
            ["game_sets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["map_id"],
            ["maps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "maps_meta",
        sa.Column("map_id", sa.BigInteger(), nullable=True),
        sa.Column("len_x", sa.Integer(), nullable=False),
        sa.Column("len_y", sa.Integer(), nullable=False),
        sa.Column("image_short_url", sa.String(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["map_id"],
            ["maps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pawns",
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("game_set_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_set_id"],
            ["game_sets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "game_set_id", "name", name="_game_set_id_pawn_uc"
        ),
    )
    op.create_table(
        "users_in_game_sets",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("game_set_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_set_id"],
            ["game_sets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "game_set_id"),
    )
    op.create_table(
        "pawns_meta",
        sa.Column("pawn_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "color",
            sqlalchemy_utils.types.color.ColorType(length=20),
            nullable=False,
        ),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pawn_id"],
            ["pawns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pawns_meta")
    op.drop_table("users_in_game_sets")
    op.drop_table("pawns")
    op.drop_table("maps_meta")
    op.drop_table("game_sets_meta")
    op.drop_table("maps")
    op.drop_index(op.f("ix_game_sets_short_url"), table_name="game_sets")
    op.drop_table("game_sets")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
