"""Make x,y allow null in PawnMeta

Revision ID: a2d5db77c2c8
Revises: e92abfb4bbce
Create Date: 2023-02-10 10:37:27.817891

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a2d5db77c2c8"
down_revision = "e92abfb4bbce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pawns_meta", "x", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "pawns_meta", "y", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pawns_meta", "y", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "pawns_meta", "x", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
