"""Add fields to pawns

Revision ID: e92abfb4bbce
Revises: b22b70a2244d
Create Date: 2023-02-10 08:51:18.876080

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e92abfb4bbce"
down_revision = "b22b70a2244d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("movable", "static", name="pawntypeenum").create(op.get_bind())
    op.add_column(
        "pawns_meta", sa.Column("visibility", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "pawns_meta",
        sa.Column(
            "type",
            sa.Enum("movable", "static", name="pawntypeenum"),
            nullable=False,
        ),
    )
    op.add_column(
        "pawns_meta", sa.Column("size_x", sa.Integer(), nullable=False)
    )
    op.add_column(
        "pawns_meta", sa.Column("size_y", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pawns_meta", "size_y")
    op.drop_column("pawns_meta", "size_x")
    op.drop_column("pawns_meta", "type")
    op.drop_column("pawns_meta", "visibility")
    sa.Enum(name="pawntypeenum").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
